# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resource/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.main_layout = QtWidgets.QHBoxLayout(MainWindow)
        self.main_layout.setContentsMargins(0, 40, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.stackedWidget = PopUpAniStackedWidget(MainWindow)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("")
        self.page_1.setObjectName("page_1")
        self.pushButton = PushButton(self.page_1)
        self.pushButton.setGeometry(QtCore.QRect(365, 240, 90, 30))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("")
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = PushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(365, 240, 90, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        self.setting_page = QtWidgets.QWidget()
        self.setting_page.setObjectName("setting_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.setting_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setting_layout = QtWidgets.QVBoxLayout()
        self.setting_layout.setSpacing(0)
        self.setting_layout.setObjectName("setting_layout")
        self.horizontalLayout_2.addLayout(self.setting_layout)
        self.stackedWidget.addWidget(self.setting_page)
        self.main_layout.addWidget(self.stackedWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyApp"))
        self.pushButton.setText(_translate("MainWindow", "page one"))
        self.pushButton_2.setText(_translate("MainWindow", "page two"))
from components.my_fluent_widgets import PushButton
from components.my_stacked_widgets import PopUpAniStackedWidget
import resource_rc
